# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdnGJ0r91au2S8rW6tikM1RGkSgJ7FQO
"""

import cv2
import os

# Function to extract frames from video
def extract_frames(video_path, output_folder):
    # Open the video file
    video = cv2.VideoCapture(video_path)

    # Check if video opened successfully
    if not video.isOpened():
        print(f"Error opening video file {video_path}")
        return

    # Frame counter
    frame_count = 0

    # Loop over frames in the video
    while True:
        # Capture frame-by-frame
        ret, frame = video.read()

        # If the frame was not grabbed, end of video
        if not ret:
            print("End of video.")
            break

        # Define frame filename
        frame_filename = os.path.join(output_folder, f"frame_{frame_count:04d}.jpg")

        # Save frame as image
        cv2.imwrite(frame_filename, frame)

        print(f"Saved {frame_filename}")

        # Increment frame count
        frame_count += 1

    # Release the video capture object
    video.release()

# Define the video path and output folder
video_path = '/content/test1].srt.mp4'
output_folder = 'extracted_frames'

# Create output folder if it doesn't exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Extract frames
extract_frames(video_path, output_folder)

"""# New Section"""

